micronaut:
  application:
    name: desafioPix

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/desafio-pix
    driverClassName: org.postgresql.Driver
    username: pix
    password: 12345678
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
